# Generated by Django 4.2.3 on 2023-08-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('av_number', models.CharField(max_length=255)),
                ('refid', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[(1, 'Audio'), (2, 'Video')], max_length=1)),
                ('process_status', models.CharField(choices=[(0, 'Pending'), (9, 'Approved'), (5, 'Rejected')], max_length=1)),
                ('rights_ids', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('aquila_id', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
