# Generated by Django 4.2.11 on 2024-03-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0003_package_resource_title_package_resource_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tree',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
