# Generated by Django 5.0.4 on 2024-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0004_package_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='undated_object',
            field=models.BooleanField(default=False),
        ),
    ]
