# Generated by Django 5.2.7 on 2025-11-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_review', '0005_package_undated_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
